#!/usr/bin/env python3
"""
Generate images-list.js from images in the images/ folder

Usage:
    python3 generate-images-list.py

This script will:
1. Scan the images/ folder
2. Find all image files (.jpg, .jpeg, .png, .gif, .webp, .bmp)
3. Generate js/modules/images-list.js with the list
"""

import os
import json
from pathlib import Path

# Configuration
IMAGES_DIR = 'images'
OUTPUT_FILE = 'js/modules/images-list.js'
ALLOWED_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.svg'}

def get_file_size_mb(filepath):
    """Get file size in MB"""
    size_bytes = os.path.getsize(filepath)
    return round(size_bytes / (1024 * 1024), 2)

def generate_images_list():
    """Generate the images list JavaScript file"""

    # Check if images directory exists
    if not os.path.exists(IMAGES_DIR):
        print(f"⚠️  Directory '{IMAGES_DIR}' does not exist!")
        print(f"Creating directory...")
        os.makedirs(IMAGES_DIR)
        print(f"✅ Created '{IMAGES_DIR}' directory")
        print(f"📁 Add your images to this folder and run the script again")
        return

    # Scan for images
    images = []
    total_size = 0

    for filename in sorted(os.listdir(IMAGES_DIR)):
        filepath = os.path.join(IMAGES_DIR, filename)

        # Skip directories
        if os.path.isdir(filepath):
            continue

        # Check extension
        ext = os.path.splitext(filename)[1].lower()
        if ext not in ALLOWED_EXTENSIONS:
            continue

        # Get file info
        file_size = get_file_size_mb(filepath)
        total_size += file_size

        # Add to list
        images.append({
            'name': filename,
            'path': f'images/{filename}',
            'size': f'{file_size} MB'
        })

        print(f"  📷 {filename} ({file_size} MB)")

    if len(images) == 0:
        print(f"⚠️  No images found in '{IMAGES_DIR}' folder")
        print(f"📁 Supported formats: {', '.join(ALLOWED_EXTENSIONS)}")

        # Create file with empty list
        write_output_file(images, 0, 0)
        return

    # Generate JavaScript file
    write_output_file(images, len(images), total_size)

    print(f"\n✅ Successfully generated {OUTPUT_FILE}")
    print(f"📊 Total: {len(images)} images, {round(total_size, 2)} MB")

def write_output_file(images, count, total_size):
    """Write the output JavaScript file"""

    # Create output directory if it doesn't exist
    output_dir = os.path.dirname(OUTPUT_FILE)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('/* =====================================================\n')
        f.write('   IMAGES-LIST.JS - Auto-generated List of Available Images\n')
        f.write('   \n')
        f.write('   🔄 Auto-generated by generate-images-list.py\n')
        f.write('   ⚠️  Do not edit this file manually!\n')
        f.write('   \n')
        f.write('   To update this list:\n')
        f.write('   1. Add/remove images in the images/ folder\n')
        f.write('   2. Run: python3 generate-images-list.py\n')
        f.write('   \n')
        f.write(f'   Total Images: {count}\n')
        f.write(f'   Total Size: {round(total_size, 2)} MB\n')
        f.write('   ===================================================== */\n\n')

        # Format images list for better readability
        f.write('export const imagesList = [\n')
        for i, img in enumerate(images):
            comma = ',' if i < len(images) - 1 else ''
            f.write(f'  {{ name: "{img["name"]}", path: "{img["path"]}" }}{comma}\n')
        f.write('];\n')

def main():
    print("🖼️  Image List Generator")
    print("=" * 50)
    print(f"📁 Scanning: {IMAGES_DIR}/")
    print(f"📝 Output:   {OUTPUT_FILE}")
    print("=" * 50 + "\n")

    generate_images_list()

    print("\n" + "=" * 50)
    print("💡 Next steps:")
    print("   1. Add images to ImageGen/images/ folder")
    print("   2. Run this script again: python3 generate-images-list.py")
    print("   3. Refresh your browser to see the changes")
    print("=" * 50)

if __name__ == '__main__':
    main()
