//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICOConvert
{

    public partial class _Default
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ImageUpload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload ImageUpload;

        /// <summary>
        /// SizeOptions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBoxList SizeOptions;

        /// <summary>
        /// ConvertButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ConvertButton;

        /// <summary>
        /// StatusLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;

        /// <summary>
        /// ResultPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ResultPanel;

        /// <summary>
        /// PreviewRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater PreviewRepeater;

        /// <summary>
        /// DownloadButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton DownloadButton;
    }
}
