/* =====================================================
   IMAGES-LIST.JS - Auto-generated List of Available Images
   
   🔄 Auto-generated by generate-images-list.py
   ⚠️  Do not edit this file manually!
   
   To update this list:
   1. Add/remove images in the images/ folder
   2. Run: python3 generate-images-list.py
   
   Total Images: 0
   Total Size: 0 MB
   ===================================================== */

export const imagesList = [
];
